"""Generate mumax3 (.mx3) scripts for the multilayered ASVI.

mumax3 has no arrays or file input, so the reservoir input sequence is
unrolled into the script: every reservoir step becomes a block of
quasi-static field steps (``Minimize()`` after each field increment), a
switch to the measurement field, and a sinc-excited dynamic run during
which the region-averaged magnetisation is written to the table every
``fmr_dt``.  The table is later split by the ``step`` column
(``asvi_rc.spectra.spectra_from_mumax3_table``).

Note mumax3's ``sinc(x)`` is sin(x)/x (unnormalised), hence the 2*pi.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np

from .geometry import Island, build_islands
from .params import ASVIParams, ProtocolParams
from .tasks import field_schedule, field_vector


def _fmt(x: float) -> str:
    return f"{x:.6g}"


def island_shape_expr(isl: Island, p: ASVIParams) -> str:
    """mumax3 shape expression for one layer-island (periodically repeated)."""
    (b0, b1), (t0, t1) = p.z_layers
    k0, k1 = (b0, b1) if isl.layer == 0 else (t0, t1)
    t = (k1 - k0) * p.cell_z
    zc = 0.5 * (k0 + k1) * p.cell_z - 0.5 * p.thickness   # mumax3 z=0 is the box centre
    if p.rounded_ends and isl.width < isl.length:
        half = (isl.length - isl.width) / 2
        shape = (f"Cuboid({_fmt(isl.length - isl.width)}, {_fmt(isl.width)}, {_fmt(t)})"
                 f".Add(Cylinder({_fmt(isl.width)}, {_fmt(t)}).Transl({_fmt(half)}, 0, 0))"
                 f".Add(Cylinder({_fmt(isl.width)}, {_fmt(t)}).Transl({_fmt(-half)}, 0, 0))")
    else:
        shape = f"Cuboid({_fmt(isl.length)}, {_fmt(isl.width)}, {_fmt(t)})"
    if isl.angle_deg:
        shape += f".RotZ({_fmt(math.radians(isl.angle_deg))})"
    # mumax3 (0,0) is the box centre; our coordinates have the origin at the box corner
    bx, by = p.box
    shape += f".Transl({_fmt(isl.cx - bx / 2)}, {_fmt(isl.cy - by / 2)}, {_fmt(zc)})"
    shape += f".Repeat({_fmt(bx)}, {_fmt(by)}, 0)"
    return shape


def header(p: ASVIParams, islands: list[Island], table_regions: bool = True) -> str:
    nx, ny, nz = p.grid
    lines = [
        "// ---- generated by asvi_rc.mumax3_writer : 3D multilayered artificial spin-vortex ice ----",
        f"// {p.n_islands} islands, box {p.box[0]*1e9:.0f} x {p.box[1]*1e9:.0f} nm, stack "
        f"NiFe {p.t_bottom*1e9:g} / Al {p.t_spacer*1e9:g} / NiFe {p.t_top*1e9:g} nm, top offset "
        f"({p.top_offset[0]*1e9:g}, {p.top_offset[1]*1e9:g}) nm",
        f"SetGridSize({nx}, {ny}, {nz})",
        f"SetCellSize({_fmt(p.cell_xy)}, {_fmt(p.cell_xy)}, {_fmt(p.cell_z)})",
        f"SetPBC({p.pbc_repetitions[0]}, {p.pbc_repetitions[1]}, {p.pbc_repetitions[2]})",
        "",
        f"Msat  = {_fmt(p.msat)}",
        f"Aex   = {_fmt(p.aex)}",
        f"alpha = {_fmt(p.alpha)}",
        "EdgeSmooth = 8",
        "",
        "// ---- geometry: one region per magnetic layer of every 3D island ----",
    ]
    names = []
    for isl in islands:
        name = f"isl{isl.index}_{'bt'[isl.layer]}"
        names.append(name)
        lines.append(f"{name} := {island_shape_expr(isl, p)}")
        lines.append(f"DefRegion({isl.region}, {name})")
    lines.append("geom := " + names[0] + "".join(f".Add({n})" for n in names[1:]))
    lines.append("SetGeom(geom)")
    lines.append("SaveAs(geom, \"geometry\")")
    lines.append("SaveAs(regions, \"regions\")")
    lines.append("")
    if table_regions:
        lines.append("// ---- table: region-averaged magnetisation (the FMR fingerprint) ----")
        for isl in islands:
            lines.append(f"TableAdd(m.Region({isl.region}))")
        lines += [
            "TableAdd(B_ext)",
            "step := 0.0",
            "B_loop := 0.0",
            "TableAddVar(step, \"step\", \"\")",
            "TableAddVar(B_loop, \"B_loop\", \"T\")",
            "",
        ]
    return "\n".join(lines)


def saturate_block(p: ASVIParams, proto: ProtocolParams, init: str = "macrospin") -> str:
    cx, cy = proto.loop_direction
    B = proto.saturation_field
    lines = ["// ---- initial state: saturate along -x (loop axis), then relax at the start field ----"]
    if init == "macrospin":
        lines.append(f"m = Uniform({_fmt(-cx)}, {_fmt(-cy)}, 0)")
    elif init == "random":
        lines.append("m = RandomMag()")
    else:
        lines.append(f"m.LoadFile(\"{init}\")")
    lines += [
        f"B_ext = vector({_fmt(-B * cx)}, {_fmt(-B * cy)}, 0)",
        "Minimize()",
        "",
    ]
    return "\n".join(lines)


def fmr_block(p: ASVIParams, b_meas_vec, step: int, b_loop: float, relax: bool = True) -> str:
    """Sinc excitation along z at fixed in-plane field, table autosave every fmr_dt."""
    bx, by, _ = b_meas_vec
    lines = [
        f"step = {float(step)}",
        f"B_loop = {_fmt(b_loop)}",
        f"B_ext = vector({_fmt(bx)}, {_fmt(by)}, 0)",
        "Minimize()" if relax else "Relax()",
        "t = 0",
        f"B_ext = vector({_fmt(bx)}, {_fmt(by)}, {_fmt(p.fmr_amp)}*sinc(2*pi*{_fmt(p.fmr_fcut)}*(t-{_fmt(p.fmr_t0)})))",
        f"TableAutoSave({_fmt(p.fmr_dt)})",
        f"Run({_fmt(p.fmr_duration)})",
        "TableAutoSave(0)",
        f"B_ext = vector({_fmt(bx)}, {_fmt(by)}, 0)",
    ]
    return "\n".join(lines)


def loop_block(ramp: np.ndarray, proto: ProtocolParams, minimizer: str = "Minimize") -> str:
    """Quasi-static field steps; the ramp already ends at the measurement field."""
    cx, cy = proto.loop_direction
    lines = []
    for b in ramp:
        lines.append(f"B_ext = vector({_fmt(b * cx)}, {_fmt(b * cy)}, 0); {minimizer}()")
    return "\n".join(lines)


def write_reservoir_script(p: ASVIParams, proto: ProtocolParams, u: np.ndarray, out_dir,
                           islands: list[Island] | None = None, minimizer: str = "Minimize",
                           save_states: bool = False, init: str = "macrospin",
                           name: str = "asvi_reservoir") -> Path:
    """Write ``<out_dir>/<name>.mx3`` plus ``<name>.meta.json`` describing it."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    islands = islands or build_islands(p)
    sched = field_schedule(u, proto)
    blocks = [header(p, islands), saturate_block(p, proto, init)]
    for k, s in enumerate(sched):
        blocks.append(f"// ================= reservoir step {k}: input {u[k]:.4f} -> B_loop {s['b_loop']*1e3:.3f} mT")
        blocks.append(loop_block(s["ramp"], proto, minimizer))
        blocks.append(fmr_block(p, field_vector(s["b_meas"], proto), k, s["b_loop"]))
        if save_states:
            blocks.append(f"SaveAs(m, \"m_step{k:04d}\")")
        blocks.append("")
    script = out_dir / f"{name}.mx3"
    script.write_text("\n".join(blocks) + "\n")
    meta = {
        "params": p.to_dict(), "protocol": proto.to_dict(),
        "islands": [i.to_dict() for i in islands],
        "region_ids": [i.region for i in islands],
        "u": [float(x) for x in u],
        "b_loop": [s["b_loop"] for s in sched],
        "b_meas": [s["b_meas"] for s in sched],
        "fmr_dt": p.fmr_dt, "fmr_nt": p.fmr_nt,
    }
    (out_dir / f"{name}.meta.json").write_text(json.dumps(meta, indent=1))
    return script


def write_field_sweep_script(p: ASVIParams, b_start: float, b_stop: float, b_step: float,
                             angle_deg: float, out_dir, islands: list[Island] | None = None,
                             presaturate: float = -0.2, init: str = "macrospin",
                             name: str = "asvi_field_sweep") -> Path:
    """FMR-vs-field map (Dion et al. Fig. 2): sweep the static field and excite at each value.

    Also records the static magnetisation per region before each excitation
    (hysteresis loop), which is what you need to calibrate the reservoir
    input range: the switching fields of the top and bottom layers.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    islands = islands or build_islands(p)
    th = math.radians(angle_deg)
    cx, cy = math.cos(th), math.sin(th)
    fields = np.arange(b_start, b_stop + 0.5 * b_step, b_step)
    blocks = [header(p, islands)]
    if init == "macrospin":
        blocks.append(f"m = Uniform({_fmt(math.copysign(cx, presaturate))}, {_fmt(math.copysign(cy, presaturate))}, 0)")
    else:
        blocks.append(f"m.LoadFile(\"{init}\")")
    blocks.append(f"B_ext = vector({_fmt(presaturate * cx)}, {_fmt(presaturate * cy)}, 0)\nMinimize()\n")
    blocks.append("SaveAs(m, \"m_presaturated\")")
    for k, b in enumerate(fields):
        blocks.append(f"// ---- field {b*1e3:.2f} mT")
        blocks.append(fmr_block(p, (b * cx, b * cy, 0.0), k, float(b)))
        blocks.append(f"SaveAs(m, \"m_field{k:04d}\")\n")
    script = out_dir / f"{name}.mx3"
    script.write_text("\n".join(blocks) + "\n")
    meta = {"params": p.to_dict(), "islands": [i.to_dict() for i in islands],
            "region_ids": [i.region for i in islands], "fields": fields.tolist(),
            "angle_deg": angle_deg, "fmr_dt": p.fmr_dt, "fmr_nt": p.fmr_nt}
    (out_dir / f"{name}.meta.json").write_text(json.dumps(meta, indent=1))
    return script
